export { default as avatarAli } from './Images/avatar-ali.png';
export { default as avatarAnisha } from './Images/avatar-anisha.png';
export { default as avatarRichard } from './Images/avatar-richard.png';
export { default as avatarShanai } from './Images/avatar-shanai.png';
export { default as bgSimplifySectionMobile } from './Images/bg-simplify-section-mobile.svg';
export { default as bgSimplifySectionDesktop } from './Images/bg-simplify-section-desktop.svg';
export { default as bgSimplifySectionTablet } from "./Images/bg-tablet-pattern.svg"
export { default as favicon } from './Images/favicon-32x32.png';
export { default as iconClose } from './Images/icon-close.svg';
export { default as iconFacebook } from './Images/icon-facebook.svg';
export { default as iconHamburger } from './Images/icon-hamburger.svg';
export { default as iconInstagram } from './Images/icon-instagram.svg';
export { default as iconPinterest } from './Images/icon-pinterest.svg';
export { default as iconTwitter } from './Images/icon-twitter.svg';
export { default as iconYouTube } from './Images/icon-youtube.svg';
export { default as illustrationIntro } from './Images/illustration-intro.svg';
export { default as logo } from './Images/logo.svg';
